# Generated by Django 4.1.5 on 2023-02-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('des', models.CharField(max_length=30)),
            ],
        ),
    ]
