# Generated by Django 4.1.5 on 2023-02-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='now',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('des', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=20)),
            ],
        ),
    ]
